apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codefresh-guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: main
  destination:
    name: do-ams3-csdp-sandbox
    namespace: cf
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
